import type {
  Workspace,
  UserAccount,
  Person,
  ParentChildRelationship,
  PartnershipRelationship,
  AuditLog,
} from '../types/index.ts';

export const INITIAL_WORKSPACE: Workspace = {
  id: 'ws-sastrohusodo-01',
  name: 'Keluarga Besar Sastrohusodo & Kusumo',
  code: 'SASTRO-2026',
  description: 'Arsip digital silsilah trah Sastrohusodo trah Yogyakarta & Surabaya',
  createdAt: '2026-10-09T08:00:00Z',
};

export const INITIAL_USERS: UserAccount[] = [
  {
    id: 'usr-superadmin-01',
    email: 'superadmin@silsilah.id',
    displayName: 'Dary Darmawan (Superadmin)',
    role: 'superadmin',
    status: 'active',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    createdAt: '2026-10-01T10:00:00Z',
  },
  {
    id: 'usr-admin-01',
    email: 'admin@silsilah.id',
    displayName: 'Bambang Sastrohusodo (Admin)',
    role: 'admin',
    status: 'active',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    createdAt: '2026-10-02T11:00:00Z',
  },
  {
    id: 'usr-client-01',
    email: 'tamu@silsilah.id',
    displayName: 'Kerabat Tamu (Client)',
    role: 'client',
    status: 'active',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    createdAt: '2026-10-05T14:30:00Z',
  },
];

export const INITIAL_PEOPLE: Person[] = [
  // --- GENERASI 1 (Kakek Buyut) ---
  {
    id: 'p-raden-hardjo',
    workspaceId: INITIAL_WORKSPACE.id,
    fullName: 'Raden Mas Hardjo Sastrohusodo',
    displayName: 'Eyang Hardjo',
    gender: 'male',
    birthDate: '1928-05-12',
    deathDate: '2005-08-17',
    isDeceased: true,
    biography: 'Perintis keluarga besar Sastrohusodo, pejuang kemerdekaan dan pendidik di Yogyakarta.',
    address: 'Jl. Malioboro No. 45, Danurejan, D.I. Yogyakarta',
    phone: '+628120000001',
    email: 'hardjo@sastrohusodo.org',
    photoUrl: 'https://images.unsplash.com/photo-1544723795-3fb6469f5b39?w=300&auto=format&fit=crop&q=80',
    verificationStatus: 'verified',
    notes: 'Makam keluarga di Kotagede, Yogyakarta',
  },
  {
    id: 'p-raden-soendari',
    workspaceId: INITIAL_WORKSPACE.id,
    fullName: 'Raden Ayu Siti Soendari',
    displayName: 'Eyang Soendari',
    gender: 'female',
    birthDate: '1932-11-20',
    deathDate: '2012-03-04',
    isDeceased: true,
    biography: 'Istri tercinta Eyang Hardjo, aktif membina kesenian membatik dan kegiatan sosial.',
    address: 'Jl. Malioboro No. 45, Danurejan, D.I. Yogyakarta',
    photoUrl: 'https://images.unsplash.com/photo-1581579438747-1dc8d17bbce4?w=300&auto=format&fit=crop&q=80',
    verificationStatus: 'verified',
  },

  // --- GENERASI 2 ---
  {
    id: 'p-bambang',
    workspaceId: INITIAL_WORKSPACE.id,
    fullName: 'Ir. Bambang Sastrohusodo',
    displayName: 'Bambang S.',
    gender: 'male',
    birthDate: '1956-06-15',
    isDeceased: false,
    biography: 'Putra sulung Eyang Hardjo. Insinyur sipil purnatugas, saat ini mengelola perkebunan dan arisan keluarga.',
    address: 'Jl. Dharmawangsa Raya No. 12, Kebayoran Baru, Jakarta Selatan',
    phone: '+628118822334',
    email: 'bambang.sastro@gmail.com',
    instagram: '@bambang_sastro',
    photoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&auto=format&fit=crop&q=80',
    verificationStatus: 'verified',
  },
  {
    id: 'p-siti-rahayu',
    workspaceId: INITIAL_WORKSPACE.id,
    fullName: 'Dra. Siti Rahayu',
    displayName: 'Ibu Rahayu',
    gender: 'female',
    birthDate: '1959-04-10',
    isDeceased: false,
    biography: 'Mantan guru bahasa Inggris SMAN 8 Jakarta, gemar memasak dan berkebun anggrek.',
    address: 'Jl. Dharmawangsa Raya No. 12, Kebayoran Baru, Jakarta Selatan',
    phone: '+628129988776',
    email: 'rahayu.siti@yahoo.com',
    instagram: '@rahayu_sastro',
    facebook: 'Siti Rahayu Sastro',
    photoUrl: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=300&auto=format&fit=crop&q=80',
    verificationStatus: 'verified',
  },
  {
    id: 'p-hendra',
    workspaceId: INITIAL_WORKSPACE.id,
    fullName: 'Ir. Hendra Sastrohusodo, M.T.',
    displayName: 'Om Hendra',
    gender: 'male',
    birthDate: '1962-09-08',
    isDeceased: false,
    biography: 'Dosen teknik di Institut Teknologi Sepuluh Nopember (ITS), tinggal di Surabaya.',
    address: 'Jl. Kertajaya Indah No. 88, Manyar Sabrangan, Surabaya',
    phone: '+6281333444555',
    email: 'hendra@its.ac.id',
    photoUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=300&auto=format&fit=crop&q=80',
    verificationStatus: 'verified',
  },
  {
    id: 'p-dewi',
    workspaceId: INITIAL_WORKSPACE.id,
    fullName: 'Dewi Anggraini, S.E.',
    displayName: 'Tante Dewi',
    gender: 'female',
    birthDate: '1965-02-14',
    isDeceased: false,
    biography: 'Wiraswasta katering tradisional dan pengurus paguyuban ibu-ibu Jawa Timur.',
    address: 'Jl. Kertajaya Indah No. 88, Surabaya',
    phone: '+628137788990',
    photoUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=300&auto=format&fit=crop&q=80',
    verificationStatus: 'verified',
  },
  {
    id: 'p-sri-wahyuni',
    workspaceId: INITIAL_WORKSPACE.id,
    fullName: 'Dr. Sri Wahyuni Sastrohusodo, Sp.A',
    displayName: 'Tante Sri (Dokter)',
    gender: 'female',
    birthDate: '1967-12-01',
    isDeceased: false,
    biography: 'Dokter spesialis anak di RSUP Dr. Kariadi Semarang.',
    address: 'Jl. Gajahmungkur No. 17, Semarang',
    phone: '+628124455667',
    email: 'dr.sriwahyuni@medika.id',
    photoUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=300&auto=format&fit=crop&q=80',
    verificationStatus: 'verified',
  },
  {
    id: 'p-agus-salim',
    workspaceId: INITIAL_WORKSPACE.id,
    fullName: 'Kolonel (Purn) Agus Salim',
    displayName: 'Om Agus',
    gender: 'male',
    birthDate: '1964-08-22',
    deathDate: '2022-01-14',
    isDeceased: true,
    biography: 'Purnawirawan TNI AD, suami almarhum dari Tante Sri Wahyuni.',
    address: 'Jl. Gajahmungkur No. 17, Semarang',
    photoUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=300&auto=format&fit=crop&q=80',
    verificationStatus: 'verified',
  },

  // --- GENERASI 3 (FOKUS UTAMA & SAUDARA/SEPUPU) ---
  {
    id: 'p-dary', // FOKUS DEFAULT
    workspaceId: INITIAL_WORKSPACE.id,
    fullName: 'Dary Darmawan Sastrohusodo',
    displayName: 'Dary (Fokus)',
    gender: 'male',
    birthDate: '1990-03-25',
    isDeceased: false,
    biography: 'Arsitek perangkat lunak dan inisiator digitalisasi arsip silsilah keluarga besar Sastrohusodo.',
    address: 'Apartemen Sudirman Tower A No. 18B, Karet Semanggi, Jakarta Selatan',
    phone: '+628119922881',
    email: 'dary.darmawan@silsilah.id',
    instagram: '@darydarmawan',
    tiktok: '@darytech',
    photoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=80',
    verificationStatus: 'verified',
  },
  {
    id: 'p-annisa',
    workspaceId: INITIAL_WORKSPACE.id,
    fullName: 'dr. Annisa Kusuma Putri',
    displayName: 'Annisa (Istri)',
    gender: 'female',
    birthDate: '1992-07-19',
    isDeceased: false,
    biography: 'Dokter umum di RS Siloam Kebon Jeruk, gemar membaca novel dan traveling.',
    address: 'Apartemen Sudirman Tower A No. 18B, Jakarta Selatan',
    phone: '+628128833445',
    email: 'annisa.kusuma@doctor.id',
    instagram: '@annisa_kusumap',
    photoUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=300&auto=format&fit=crop&q=80',
    verificationStatus: 'verified',
  },
  {
    id: 'p-maya',
    workspaceId: INITIAL_WORKSPACE.id,
    fullName: 'Maya Sastrohusodo, M.Ds.',
    displayName: 'Maya Sastro',
    gender: 'female',
    birthDate: '1993-10-05',
    isDeceased: false,
    biography: 'Desainer grafis & ilustrator buku cerita anak, tinggal di Bandung.',
    address: 'Jl. Riau No. 56, Bandung',
    phone: '+628156677889',
    email: 'maya.illustration@gmail.com',
    instagram: '@mayasastro_art',
    photoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=80',
    verificationStatus: 'verified',
  },
  {
    id: 'p-fajar',
    workspaceId: INITIAL_WORKSPACE.id,
    fullName: 'Fajar Ramadhan, S.T.',
    displayName: 'Fajar (Ipar)',
    gender: 'male',
    birthDate: '1991-01-18',
    isDeceased: false,
    biography: 'Suami dari Maya, arsitek lanskap di studio desain Bandung.',
    address: 'Jl. Riau No. 56, Bandung',
    phone: '+628178899001',
    photoUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=300&auto=format&fit=crop&q=80',
    verificationStatus: 'verified',
  },
  {
    id: 'p-rizky',
    workspaceId: INITIAL_WORKSPACE.id,
    fullName: 'Rizky Pratama Sastrohusodo',
    displayName: 'Rizky (Adik)',
    gender: 'male',
    birthDate: '1998-12-30',
    isDeceased: false,
    biography: 'Adik bungsu Dary, mahasiswa pascasarjana manajemen bisnis di UGM Yogyakarta.',
    address: 'Pogung Baru Blok F, Sleman, D.I. Yogyakarta',
    phone: '+628190011223',
    instagram: '@rizky_sastro',
    photoUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=300&auto=format&fit=crop&q=80',
    verificationStatus: 'verified',
  },
  {
    id: 'p-farhan',
    workspaceId: INITIAL_WORKSPACE.id,
    fullName: 'Farhan Sastrohusodo, B.Eng',
    displayName: 'Farhan (Sepupu)',
    gender: 'male',
    birthDate: '1994-05-14',
    isDeceased: false,
    biography: 'Putra dari Om Hendra, konsultan energi terbarukan di Jakarta.',
    address: 'Tebet Timur Dalam VII No. 3, Jakarta Selatan',
    phone: '+628123344991',
    photoUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=300&auto=format&fit=crop&q=80',
    verificationStatus: 'verified',
  },
  {
    id: 'p-nadia',
    workspaceId: INITIAL_WORKSPACE.id,
    fullName: 'Nadia Sastrohusodo, S.Psi',
    displayName: 'Nadia (Sepupu)',
    gender: 'female',
    birthDate: '1997-08-27',
    isDeceased: false,
    biography: 'Putri dari Om Hendra, psikolog klinis di Surabaya.',
    address: 'Kertajaya Indah No. 88, Surabaya',
    phone: '+628131122338',
    photoUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=300&auto=format&fit=crop&q=80',
    verificationStatus: 'verified',
  },
  {
    id: 'p-dimas',
    workspaceId: INITIAL_WORKSPACE.id,
    fullName: 'Dimas Salim, S.Kom',
    displayName: 'Dimas (Sepupu)',
    gender: 'male',
    birthDate: '1995-04-03',
    isDeceased: false,
    biography: 'Putra dari Tante Sri Wahyuni, game developer di Yogyakarta.',
    address: 'Jl. Kaliurang KM 5, Yogyakarta',
    phone: '+628127766554',
    photoUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=300&auto=format&fit=crop&q=80',
    verificationStatus: 'verified',
  },
  {
    id: 'p-putri',
    workspaceId: INITIAL_WORKSPACE.id,
    fullName: 'Putri Ayu Salim',
    displayName: 'Putri (Sepupu)',
    gender: 'female',
    birthDate: '1999-11-11',
    isDeceased: false,
    biography: 'Putri dari Tante Sri Wahyuni, dokter muda (koas) di Semarang.',
    address: 'Jl. Gajahmungkur No. 17, Semarang',
    phone: '+628139988112',
    photoUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=300&auto=format&fit=crop&q=80',
    verificationStatus: 'verified',
  },

  // --- GENERASI 4 (CUCU & KEPONAKAN) ---
  {
    id: 'p-kenzo',
    workspaceId: INITIAL_WORKSPACE.id,
    fullName: 'Kenzo Alfarizi Sastrohusodo',
    displayName: 'Kenzo (Anak)',
    gender: 'male',
    birthDate: '2019-09-12',
    isDeceased: false,
    biography: 'Putra pertama Dary & Annisa. Sangat suka dinosaurus dan menggambar mobil balap.',
    address: 'Apartemen Sudirman Tower A No. 18B, Jakarta Selatan',
    photoUrl: 'https://images.unsplash.com/photo-1502086223501-7ea6ecd79368?w=300&auto=format&fit=crop&q=80',
    verificationStatus: 'verified',
  },
  {
    id: 'p-keisha',
    workspaceId: INITIAL_WORKSPACE.id,
    fullName: 'Keisha Nayla Sastrohusodo',
    displayName: 'Keisha (Anak)',
    gender: 'female',
    birthDate: '2022-04-05',
    isDeceased: false,
    biography: 'Putri kedua Dary & Annisa, periang dan suka menari balet.',
    address: 'Apartemen Sudirman Tower A No. 18B, Jakarta Selatan',
    photoUrl: 'https://images.unsplash.com/photo-1519689680058-324335c77eba?w=300&auto=format&fit=crop&q=80',
    verificationStatus: 'verified',
  },
  {
    id: 'p-arka',
    workspaceId: INITIAL_WORKSPACE.id,
    fullName: 'Arka Rayyan Ramadhan',
    displayName: 'Arka (Keponakan)',
    gender: 'male',
    birthDate: '2023-08-20',
    isDeceased: false,
    biography: 'Putra pertama pasangan Maya & Fajar.',
    address: 'Jl. Riau No. 56, Bandung',
    photoUrl: 'https://images.unsplash.com/photo-1485546246426-74dc88dec4d9?w=300&auto=format&fit=crop&q=80',
    verificationStatus: 'verified',
  },
];

export const INITIAL_PARTNERSHIPS: PartnershipRelationship[] = [
  // Gen 1
  {
    id: 'part-01',
    workspaceId: INITIAL_WORKSPACE.id,
    personAId: 'p-raden-hardjo',
    personBId: 'p-raden-soendari',
    relationshipType: 'married',
    startDate: '1952-08-10',
    status: 'past',
    notes: 'Pernikahan adat Yogyakarta langgeng hingga akhir hayat',
  },
  // Gen 2
  {
    id: 'part-02',
    workspaceId: INITIAL_WORKSPACE.id,
    personAId: 'p-bambang',
    personBId: 'p-siti-rahayu',
    relationshipType: 'married',
    startDate: '1987-11-28',
    status: 'current',
  },
  {
    id: 'part-03',
    workspaceId: INITIAL_WORKSPACE.id,
    personAId: 'p-hendra',
    personBId: 'p-dewi',
    relationshipType: 'married',
    startDate: '1992-06-12',
    status: 'current',
  },
  {
    id: 'part-04',
    workspaceId: INITIAL_WORKSPACE.id,
    personAId: 'p-sri-wahyuni',
    personBId: 'p-agus-salim',
    relationshipType: 'married',
    startDate: '1993-09-04',
    status: 'past',
    notes: 'Almarhum Om Agus wafat tahun 2022',
  },
  // Gen 3
  {
    id: 'part-05',
    workspaceId: INITIAL_WORKSPACE.id,
    personAId: 'p-dary',
    personBId: 'p-annisa',
    relationshipType: 'married',
    startDate: '2018-12-15',
    status: 'current',
    notes: 'Akad di Masjid Istiqlal Jakarta',
  },
  {
    id: 'part-06',
    workspaceId: INITIAL_WORKSPACE.id,
    personAId: 'p-maya',
    personBId: 'p-fajar',
    relationshipType: 'married',
    startDate: '2021-03-20',
    status: 'current',
  },
];

export const INITIAL_PARENT_CHILD: ParentChildRelationship[] = [
  // Gen 1 -> Gen 2 (Anak Raden Hardjo & Raden Soendari)
  {
    id: 'pc-01',
    workspaceId: INITIAL_WORKSPACE.id,
    parentPersonId: 'p-raden-hardjo',
    childPersonId: 'p-bambang',
    parentRole: 'father',
    parentageType: 'biological',
    verifiedStatus: 'verified',
  },
  {
    id: 'pc-02',
    workspaceId: INITIAL_WORKSPACE.id,
    parentPersonId: 'p-raden-soendari',
    childPersonId: 'p-bambang',
    parentRole: 'mother',
    parentageType: 'biological',
    verifiedStatus: 'verified',
  },
  {
    id: 'pc-03',
    workspaceId: INITIAL_WORKSPACE.id,
    parentPersonId: 'p-raden-hardjo',
    childPersonId: 'p-hendra',
    parentRole: 'father',
    parentageType: 'biological',
    verifiedStatus: 'verified',
  },
  {
    id: 'pc-04',
    workspaceId: INITIAL_WORKSPACE.id,
    parentPersonId: 'p-raden-soendari',
    childPersonId: 'p-hendra',
    parentRole: 'mother',
    parentageType: 'biological',
    verifiedStatus: 'verified',
  },
  {
    id: 'pc-05',
    workspaceId: INITIAL_WORKSPACE.id,
    parentPersonId: 'p-raden-hardjo',
    childPersonId: 'p-sri-wahyuni',
    parentRole: 'father',
    parentageType: 'biological',
    verifiedStatus: 'verified',
  },
  {
    id: 'pc-06',
    workspaceId: INITIAL_WORKSPACE.id,
    parentPersonId: 'p-raden-soendari',
    childPersonId: 'p-sri-wahyuni',
    parentRole: 'mother',
    parentageType: 'biological',
    verifiedStatus: 'verified',
  },

  // Gen 2 -> Gen 3 (Anak Bambang & Siti Rahayu)
  {
    id: 'pc-07',
    workspaceId: INITIAL_WORKSPACE.id,
    parentPersonId: 'p-bambang',
    childPersonId: 'p-dary',
    parentRole: 'father',
    parentageType: 'biological',
    verifiedStatus: 'verified',
  },
  {
    id: 'pc-08',
    workspaceId: INITIAL_WORKSPACE.id,
    parentPersonId: 'p-siti-rahayu',
    childPersonId: 'p-dary',
    parentRole: 'mother',
    parentageType: 'biological',
    verifiedStatus: 'verified',
  },
  {
    id: 'pc-09',
    workspaceId: INITIAL_WORKSPACE.id,
    parentPersonId: 'p-bambang',
    childPersonId: 'p-maya',
    parentRole: 'father',
    parentageType: 'biological',
    verifiedStatus: 'verified',
  },
  {
    id: 'pc-10',
    workspaceId: INITIAL_WORKSPACE.id,
    parentPersonId: 'p-siti-rahayu',
    childPersonId: 'p-maya',
    parentRole: 'mother',
    parentageType: 'biological',
    verifiedStatus: 'verified',
  },
  {
    id: 'pc-11',
    workspaceId: INITIAL_WORKSPACE.id,
    parentPersonId: 'p-bambang',
    childPersonId: 'p-rizky',
    parentRole: 'father',
    parentageType: 'biological',
    verifiedStatus: 'verified',
  },
  {
    id: 'pc-12',
    workspaceId: INITIAL_WORKSPACE.id,
    parentPersonId: 'p-siti-rahayu',
    childPersonId: 'p-rizky',
    parentRole: 'mother',
    parentageType: 'biological',
    verifiedStatus: 'verified',
  },

  // Gen 2 -> Gen 3 (Anak Hendra & Dewi)
  {
    id: 'pc-13',
    workspaceId: INITIAL_WORKSPACE.id,
    parentPersonId: 'p-hendra',
    childPersonId: 'p-farhan',
    parentRole: 'father',
    parentageType: 'biological',
    verifiedStatus: 'verified',
  },
  {
    id: 'pc-14',
    workspaceId: INITIAL_WORKSPACE.id,
    parentPersonId: 'p-dewi',
    childPersonId: 'p-farhan',
    parentRole: 'mother',
    parentageType: 'biological',
    verifiedStatus: 'verified',
  },
  {
    id: 'pc-15',
    workspaceId: INITIAL_WORKSPACE.id,
    parentPersonId: 'p-hendra',
    childPersonId: 'p-nadia',
    parentRole: 'father',
    parentageType: 'biological',
    verifiedStatus: 'verified',
  },
  {
    id: 'pc-16',
    workspaceId: INITIAL_WORKSPACE.id,
    parentPersonId: 'p-dewi',
    childPersonId: 'p-nadia',
    parentRole: 'mother',
    parentageType: 'biological',
    verifiedStatus: 'verified',
  },

  // Gen 2 -> Gen 3 (Anak Sri Wahyuni & Agus Salim)
  {
    id: 'pc-17',
    workspaceId: INITIAL_WORKSPACE.id,
    parentPersonId: 'p-sri-wahyuni',
    childPersonId: 'p-dimas',
    parentRole: 'mother',
    parentageType: 'biological',
    verifiedStatus: 'verified',
  },
  {
    id: 'pc-18',
    workspaceId: INITIAL_WORKSPACE.id,
    parentPersonId: 'p-agus-salim',
    childPersonId: 'p-dimas',
    parentRole: 'father',
    parentageType: 'biological',
    verifiedStatus: 'verified',
  },
  {
    id: 'pc-19',
    workspaceId: INITIAL_WORKSPACE.id,
    parentPersonId: 'p-sri-wahyuni',
    childPersonId: 'p-putri',
    parentRole: 'mother',
    parentageType: 'biological',
    verifiedStatus: 'verified',
  },
  {
    id: 'pc-20',
    workspaceId: INITIAL_WORKSPACE.id,
    parentPersonId: 'p-agus-salim',
    childPersonId: 'p-putri',
    parentRole: 'father',
    parentageType: 'biological',
    verifiedStatus: 'verified',
  },

  // Gen 3 -> Gen 4 (Anak Dary & Annisa)
  {
    id: 'pc-21',
    workspaceId: INITIAL_WORKSPACE.id,
    parentPersonId: 'p-dary',
    childPersonId: 'p-kenzo',
    parentRole: 'father',
    parentageType: 'biological',
    verifiedStatus: 'verified',
  },
  {
    id: 'pc-22',
    workspaceId: INITIAL_WORKSPACE.id,
    parentPersonId: 'p-annisa',
    childPersonId: 'p-kenzo',
    parentRole: 'mother',
    parentageType: 'biological',
    verifiedStatus: 'verified',
  },
  {
    id: 'pc-23',
    workspaceId: INITIAL_WORKSPACE.id,
    parentPersonId: 'p-dary',
    childPersonId: 'p-keisha',
    parentRole: 'father',
    parentageType: 'biological',
    verifiedStatus: 'verified',
  },
  {
    id: 'pc-24',
    workspaceId: INITIAL_WORKSPACE.id,
    parentPersonId: 'p-annisa',
    childPersonId: 'p-keisha',
    parentRole: 'mother',
    parentageType: 'biological',
    verifiedStatus: 'verified',
  },

  // Gen 3 -> Gen 4 (Anak Maya & Fajar)
  {
    id: 'pc-25',
    workspaceId: INITIAL_WORKSPACE.id,
    parentPersonId: 'p-maya',
    childPersonId: 'p-arka',
    parentRole: 'mother',
    parentageType: 'biological',
    verifiedStatus: 'verified',
  },
  {
    id: 'pc-26',
    workspaceId: INITIAL_WORKSPACE.id,
    parentPersonId: 'p-fajar',
    childPersonId: 'p-arka',
    parentRole: 'father',
    parentageType: 'biological',
    verifiedStatus: 'verified',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'log-01',
    workspaceId: INITIAL_WORKSPACE.id,
    actorUserId: 'usr-superadmin-01',
    actorName: 'Dary Darmawan (Superadmin)',
    actorRole: 'superadmin',
    action: 'CREATE_PERSON',
    targetType: 'person',
    targetId: 'p-arka',
    timestamp: '2026-10-08T15:20:00Z',
    summary: 'Menambahkan anggota baru: Arka Rayyan Ramadhan (Generasi ke-4)',
  },
  {
    id: 'log-02',
    workspaceId: INITIAL_WORKSPACE.id,
    actorUserId: 'usr-admin-01',
    actorName: 'Bambang Sastrohusodo (Admin)',
    actorRole: 'admin',
    action: 'CREATE_PARENT_CHILD',
    targetType: 'relationship',
    targetId: 'pc-25',
    timestamp: '2026-10-08T15:25:00Z',
    summary: 'Menghubungkan relasi orang tua: Maya Sastrohusodo -> Arka Rayyan',
  },
  {
    id: 'log-03',
    workspaceId: INITIAL_WORKSPACE.id,
    actorUserId: 'usr-superadmin-01',
    actorName: 'Dary Darmawan (Superadmin)',
    actorRole: 'superadmin',
    action: 'CHANGE_ROLE',
    targetType: 'user',
    targetId: 'usr-client-01',
    timestamp: '2026-10-09T07:15:00Z',
    summary: 'Memperbarui role akun tamu@silsilah.id menjadi Client (Read-Only)',
  },
];
